import time
import json
import subprocess
import datetime
import aiomysql
import psutil
import pypika
import os
import asyncio as aio
import traceback
import uuid
import shutil
import psutil

from fastapi import FastAPI, Request, APIRouter
from fastapi.responses import *
from pydantic import BaseModel
from typing import Any

import LCRadio
import yggdrasil

class MySQLConnectionPool:
    def __init__(self) -> None:
        self.pool = None
    async def initialize(self):
        self.pool = await aiomysql.create_pool(
            host='127.0.0.1',
            port=3306,
            user='MnlSmile',
            password=os.getenv('MYSQL_PASSWORD'),
            db='linchan3-competition',
            minsize=1,
            maxsize=10,
            autocommit=False
        )
    async def acquire(self):
        if self.pool is None:
            await self.initialize()
        return await self.pool.acquire()
    async def close(self):
        if self.pool:
            self.pool.close()
            await self.pool.wait_closed()

pool = MySQLConnectionPool()

app = FastAPI()
api = APIRouter(prefix='/LinChan3-Competition/api/v1')
web = APIRouter(prefix='/LinChan3-Competition/web')
app.include_router(LCRadio.api)
app.include_router(yggdrasil.api)

def disable(*args, **kwargs):
    def _(*args, **kwargs): return
    return _

@app.on_event("startup")
#@disable
async def startup_event():
    await pool.initialize()

class POFMetadata(BaseModel):
    uuid:str
    id:int
    creationTime:int
    version:str
    minecraftVersion:str
    playersCount:int
    playerList:list[str]
    game:str
    LCCompetitionServerVersion:str
    replayFilePath:str
    replayRemotePath:str
    started:bool
    canceled:bool
    finished:bool
    startReason:str
    cancelReason:str
    finishReason:str
    startTime:int
    finishTime:int
    ranking:list[dict]
    data:dict

test_uuid_id_map = {}

# Generated by AI
def get_processes_by_port(port):
    result = []
    
    for conn in psutil.net_connections():
        if hasattr(conn.laddr, 'port') and conn.laddr.port == port:
            try:
                process = psutil.Process(conn.pid)
                process_info = {
                    'pid': process.pid,
                    'name': process.name(),
                    'status': conn.status,
                    'local_address': f"{conn.laddr.ip}:{conn.laddr.port}",
                    'remote_address': f"{conn.raddr.ip}:{conn.raddr.port}" if conn.raddr else None,
                    'create_time': process.create_time(),
                    'exe_path': process.exe(),
                    'cmdline': ' '.join(process.cmdline())
                }
                result.append(process_info)
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                continue
    
    return result

@api.post('/pillars_of_fortune/download_metadata')
async def download_metadata(metadata:POFMetadata) -> POFMetadata:
    global test_uuid_id_map
    
    conn = await pool.acquire()
    try:
        async with conn.cursor() as cur:
            pof = pypika.Table('pillars_of_fortune')
            max_retries = 10
            retry_count = 0
            
            while retry_count < max_retries:
                query = pypika.MySQLQuery.from_(pof).select(pof.uuid).where(pof.uuid == metadata.uuid)
                await cur.execute(str(query))
                result = await cur.fetchall()
                
                if len(result) > 0:
                    metadata.uuid = str(uuid.uuid4())
                    retry_count += 1
                else:

                    break
            
            if retry_count >= max_retries:
                timestamp = int(time.time() * 1000)
                metadata.uuid = f"gen-{timestamp}"
            
            metadata.creationTime = int(time.time() * 1000)
            metadata.LCCompetitionServerVersion = '0.9.0'

            query = pypika.MySQLQuery.into(pof).columns(
                'uuid', 'creationTime', 'version', 'LCCompetitionServerVersion'
            ).insert(
                metadata.uuid, 
                metadata.creationTime, 
                metadata.version, 
                metadata.LCCompetitionServerVersion
            )
            
            await cur.execute(str(query))
            await conn.commit()

            await cur.execute("SELECT LAST_INSERT_ID()")
            result = await cur.fetchone()
            if result and result[0]:
                metadata.id = result[0]

            test_uuid_id_map[metadata.uuid] = metadata.id
            
    except Exception as e:
        traceback.print_exc()
        if conn:
            await conn.rollback()
    finally:
        if conn:
            pool.pool.release(conn)
    
    return metadata

@api.get('/pillars_of_fortune/get_time_millisec')
async def get_time_millisec() -> dict:
    return {"time": time.time() * 1000}

@api.post('/pillars_of_fortune/require_start')
async def require_start(metadata:POFMetadata) -> POFMetadata:
    return metadata

@api.post('/pillars_of_fortune/require_close')
async def require_close(metadata:POFMetadata, req:Request) -> dict:
    if req.client.host in ['127.0.0.1']:
        procs = get_processes_by_port(req.client.port)
        if len(procs) > 0:
            for proc in procs:
                if proc['name'] == 'bedrock_server.exe' or 'bedrock_server.exe' in proc['exe_path']:
                    try:
                        subprocess.run(f'taskkill /F /PID {proc['pid']}', shell=True, check=True)
                        print(f"已终止进程 PID: {proc['pid']}")
                    except subprocess.CalledProcessError as e:
                        print(f"终止进程失败: {e}")
                        traceback.print_exception(e)
        return {'status': 'ok'}
    else:
        return {'status': 'failed'}

@api.post('/pillars_of_fortune/upload_result')
async def upload_result(metadata:POFMetadata) -> dict:
    db = await pool.acquire()
    async with db.cursor() as cur:
        pof = pypika.Table('pillars_of_fortune')
        query = pypika.MySQLQuery.update(pof) \
            .set(pof.creationTime, metadata.creationTime) \
            .set(pof.version, metadata.version) \
            .set(pof.minecraftVersion, metadata.minecraftVersion) \
            .set(pof.playersCount, metadata.playersCount) \
            .set(pof.playerList, json.dumps(metadata.playerList)) \
            .set(pof.game, metadata.game) \
            .set(pof.LCCompetitionServerVersion, metadata.LCCompetitionServerVersion) \
            .set(pof.replayFilePath, metadata.replayFilePath) \
            .set(pof.replayRemotePath, metadata.replayRemotePath) \
            .set(pof.started, int(metadata.started)) \
            .set(pof.canceled, int(metadata.canceled)) \
            .set(pof.finished, int(metadata.finished)) \
            .set(pof.startReason, metadata.startReason) \
            .set(pof.cancelReason, metadata.cancelReason) \
            .set(pof.finishReason, metadata.finishReason) \
            .set(pof.startTime, metadata.startTime) \
            .set(pof.finishTime, metadata.finishTime) \
            .set(pof.ranking, json.dumps(metadata.ranking)) \
            .set(pof.data, json.dumps(metadata.data)) \
            .where(pof.id == metadata.id)
        try:
            await cur.execute(str(query))
            await db.commit()
        except Exception as e:
            traceback.print_exception(e)
            await db.rollback()
    return {}

# https://idlist.projectxero.top/data/beta/vanilla.json
@api.get('/pillars_of_fortune/download_minecraft_item_list')
async def download_minecraft_item_list(version:str='0.1.21.131') -> dict:
    with open('./minecraft_be_manifests_1.21.131.json', 'r', encoding='utf-8') as f:
        return json.load(f)['enums']['item']

@api.get('/pillars_of_fortune/query_match')
async def query_match(id:int) -> Response:
    db = await pool.acquire()
    async with db.cursor() as cur:
        pof = pypika.Table('pillars_of_fortune')
        retry_count = 0
        while retry_count < 10:
            query = pypika.MySQLQuery.from_(pof).select(
                pof.uuid,
                pof.id,
                pof.creationTime,
                pof.version,
                pof.minecraftVersion,
                pof.playersCount,
                pof.playerList,
                pof.game,
                pof.LCCompetitionServerVersion,
                pof.replayFilePath,
                pof.replayRemotePath,
                pof.started,
                pof.canceled,
                pof.finished,
                pof.startReason,
                pof.cancelReason,
                pof.finishReason,
                pof.startTime,
                pof.finishTime,
                pof.ranking,
                pof.data
            )
            await cur.execute(str(query))
            result = await cur.fetchall()
            if len(result):
                return dict(result[0])
            else:
                retry_count += 1

@web.get('/POF/history')
async def web_POF_history() -> FileResponse:
    return FileResponse('./POF/history.html')

@api.get('/common/server_status')
async def server_status() -> dict:
    cpu = psutil.cpu_percent()
    _mem = psutil.virtual_memory()
    ram = [_mem.total, _mem.used, _mem.percent]
    return {
        "cpu": cpu,
        "ram": ram
    }


app.include_router(api)
app.include_router(web)