# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: LCAuthorization.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'LCAuthorization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15LCAuthorization.proto\"4\n\x08\x45nvelope\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"k\n PushNewestAuthorizationCodeQuery\x12\x11\n\ttask_uuid\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x18\n\x10original_message\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\x03\"8\n#PushNewestAuthorizationCodeResponse\x12\x11\n\ttask_uuid\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LCAuthorization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVELOPE']._serialized_start=25
  _globals['_ENVELOPE']._serialized_end=77
  _globals['_PUSHNEWESTAUTHORIZATIONCODEQUERY']._serialized_start=79
  _globals['_PUSHNEWESTAUTHORIZATIONCODEQUERY']._serialized_end=186
  _globals['_PUSHNEWESTAUTHORIZATIONCODERESPONSE']._serialized_start=188
  _globals['_PUSHNEWESTAUTHORIZATIONCODERESPONSE']._serialized_end=244
# @@protoc_insertion_point(module_scope)
